runtime: python39
entrypoint: gunicorn -b :$PORT index:app

instance_class: F2

env_variables:
  DATABASE_URI: "/cloudsql/cineflask:us-central1:ger2430"

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.8

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto